### ISSUE TITLE
Update Visium auxiliary component name

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/hdash_air#1]
@PozhidayevaDarya recently implemented a name change for the Visium Auxiliary Files component

The supported component in hdash should be changed from`10xVisiumSpatialTranscriptomics-AuxiliaryFilesLevel2` to
`10xVisiumSpatialTranscriptomics-AuxiliaryFiles`

**Comment by ecerami** [comment]
Thanks @clarisse-lau.  This is now fixed.  Will be auto deployed at 6:00 pm EST.

**Comment by clarisse-lau** [comment]
Thank you @ecerami !!
