### ISSUE TITLE
Add Slide-seq and ExSeqMinimal to hdash

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/hdash_air#14]
Add support for Slide-seq manifests to hdash. New metadata tables are available from HTAPP: https://hdash.website-us-east-1.linodeobjects.com/HTA1.html

Component names:
- Slide-seqLevel1
- Slide-seqLevel2
- Slide-seqLevel3

**Comment by clarisse-lau** [comment]
The new `ExSeqMinimal` template can be validated in the same manner as `OtherAssay`

**Comment by ecerami** [comment]
thanks @clarisse-lau this is now done and deployed.
