### ISSUE TITLE
Error for filenames containing any character outside of acceptable character set

### ISSUE THREAD

**Issue by alexeliotlash** [ncihtan/hdash_air#16]
In order to conform to CDS standards, generate an error for any filename that contains a character outside of the following set:
a-z
A-Z
0-9
period(.)
dash (-)
underscore (_)

**Comment by ecerami** [comment]
@alexeliotlash going to work on this one next.  can you confirm this is still needed?

**Comment by ecerami** [comment]
this is now in progress.  See new validation messages at:  https://hdash.website-us-east-1.linodeobjects.com/index.html

**Comment by ecerami** [comment]
This is now fixed and deployed!
