### ISSUE TITLE
Add support for new data types/levels

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/hdash_air#3]
- 10xVisiumSpatialTranscriptomics-RNA-seqLevel4
- BulkMethylation-seqLevel1
- BulkMethylation-seqLevel2
- BulkMethylation-seqLevel3
- HI-C-seqLevel1
- HI-C-seqLevel2
- HI-C-seqLevel3
- MassSpectrometryLevel1 
- MassSpectrometryLevel2
- MassSpectrometryLevel3
- MassSpectrometryLevel4
- MassSpectrometryAuxiliaryFile
- ElectronMicroscopyLevel1
- ElectronMicroscopyLevel2
- ElectronMicroscopyLevel3
- ElectronMicroscopyLevel4

We don't have metadata submissions for all of the above, but adding in anticipation.

**Comment by clarisse-lau** [comment]
cc @aclayton555 @adamjtaylor in case I missed any

**Comment by aclayton555** [comment]
I think we are missing electron microscopy - the OHSU team is in the process of submitting these data as these template just rolled out in our last sprint

**Comment by clarisse-lau** [comment]
Thanks, added!

**Comment by ecerami** [comment]
A few of these are actually in the Stanford data set.  See #4

**Comment by clarisse-lau** [comment]
Yep, thanks @ecerami! 
This was meant to be the comprehensive list of all assay types newly supported in the DCA, covering those we have already received annotations for (Stanford) and others we expect to receive soon.

**Comment by alexeliotlash** [comment]
Should the new data types be summarized in the "completeness" plots?

Perhaps add the following data types to "Assay Matrix: Bulk Data":
10xVisiumSpatialTranscriptomics-RNA-seqLevel4
BulkMethylation-seqLevel1
BulkMethylation-seqLevel2
BulkMethylation-seqLevel3
HI-C-seqLevel1
HI-C-seqLevel2
HI-C-seqLevel3

Perhaps add the following data types to "Assay Matrix: Imaging and Other":
MassSpectrometryLevel1
MassSpectrometryLevel2
MassSpectrometryLevel3
MassSpectrometryLevel4
MassSpectrometryAuxiliaryFile
ElectronMicroscopyLevel1
ElectronMicroscopyLevel2
ElectronMicroscopyLevel3
ElectronMicroscopyLevel4

**Comment by alexeliotlash** [comment]
I see there is a "Assay Matrix: Visium" plot, so 10xVisiumSpatialTranscriptomics-RNA-seqLevel4
should be added to that.

**Comment by ecerami** [comment]
I am modifying things now to have 6 matrices:
* Clinical Data Matrix: Tiers 1 and 2
* Clinical Data Matrix: Tier 3
* Assay Matrix: Single Cell Data
* Assay Matrix: Bulk Data
* Assay Matrix: Core Imaging
* Assay Matrix: Other

**Comment by ecerami** [comment]
New matrix support is now deployed.  e.g. see. http://hdash.website-us-east-1.linodeobjects.com/HTA12.html
