### ISSUE TITLE
Add Percent Metadata Complete to top-level summary table

### ISSUE THREAD

**Issue by alexeliotlash** [ncihtan/hdash_air#5]
Add a new column with "Percent Metadata Complete" (as seen at the top of <http://hdash.website-us-east-1.linodeobjects.com/HTA5.html>) to the top-level summary table at <http://hdash.website-us-east-1.linodeobjects.com/>.

**Comment by ecerami** [comment]
@alexeliotlash this is in progress.  should be deployed tomorrow.

**Comment by ecerami** [comment]
This is now deployed.  See:  http://hdash.website-us-east-1.linodeobjects.com/index.html
