### ISSUE TITLE
Add new data type level completeness table to center summary page

### ISSUE THREAD

**Issue by alexeliotlash** [ncihtan/hdash_air#6]
Below the "Metadata Files" table on the center summary page, add a table with biospecimen id counts for data type by level.

Rows:
10xVisiumSpatialTranscriptomics-RNA-seq
BulkRNA-seq
BulkWES
Imaging
ScATAC-seq
ScRNA-seq

Columns:
Level_1
Level_2
Level_3
Level_4

**Comment by ecerami** [comment]
@alexeliotlash I think this data is already available on the page, e.g. under Assay Matrix: Single Cell Data, you can click View Details, and scroll all the way down.

**Comment by alexeliotlash** [comment]
Correct.  The data is there but requires multiple clicks to get to.  I think the idea was to surface these counts up to the top and put them all in a single table with data types in the rows and levels in the columns.

**Comment by alexeliotlash** [comment]
I guess it's a nice-to-have.  It would provide a quick overview or data completeness across levels and might be useful for liaisons and NCI.

**Comment by ecerami** [comment]
Since this is "nice to have" am going ahead closing this one.
