### ISSUE TITLE
Add redirects from old center-specific dashboard pages to new center-specific dashboard changes

### ISSUE THREAD

**Issue by aclayton555** [ncihtan/hdash_air#9]
For ease of navigation, one of our collaborators at HMS noted that it would be helpful to have the former center-specific dashboard pages (e.g. for SARDANA: http://htan_dashboard.surge.sh/syn24984270.html) redirect to the new version of each center-specific dashboard page (e.g. for SARDANA: http://hdash.website-us-east-1.linodeobjects.com/HTA13.html).

It is likely that multiple staff across the centers have their center's respective dashboard page bookmarked, so this would streamline the transition and navigation for the former to the new dashboard. This convenience feature would be helpful for centers and would be similar to the existing redirect from the former dashboard homepage (see redirect at see on http://htan_dashboard.surge.sh/) to the new dashboard.

**Comment by ecerami** [comment]
@aclayton555 this one is quite old.  OK if I close?

**Comment by aclayton555** [comment]
Probably okay to close.

RIP old dashboard
